name: MaceForWuh
version: 1.0
author: Wuh
main: com.wuh.maceforwuh.MaceForWuh
api-version: 1.20
description: A custom mace plugin that shatters shields!

commands:
  wuhsmace:
    description: Gives you Wuh's Mace.
    usage: /wuhsmace
    permission: wuhsmace.give
